### ISSUE TITLE
Worse asm with latest MBG vs 1.0.12 release

### ISSUE THREAD

**Issue by skoren** [maickrau/MBG#18]
In the new_mbg/bonobo folder, there are 36 t2t scaffolds in the original MBG version vs 24 w/new. The files t2t_scaffolds_by_chr list the t2t scaffolds and their chromosome IDs. These both used trio-split reads and graphs for mapping. 

Most missing chromosomes seem to have a telomere on one end (e.g. chrX/Y, chr16, chr2B) but are slightly shorter than in the old version. Not sure why the very end is being lost.

**Comment by ptrebert** [comment]
@maickrau 
can you comment on this / which versions exactly are now recommended?
I have two samples where Verkko v1.2 fails with an AssertionError in MBG v1.0.12, and it is unclear to me if rerunning with v1.0.13 could possibly fix this but make these two assemblies worse compared to the others?

**Comment by skoren** [comment]
The latest release 1.0.13 or even tip should be OK to use. The change that was making some assemblies worse is disabled by default.

**Comment by ptrebert** [comment]
thanks for the hint
