### ISSUE TITLE
Error from UnitigResolver addPathButFirstMaybeTrim

### ISSUE THREAD

**Issue by slmcevoy** [maickrau/MBG#19]
Hi,

I'm trying to run Verkko on some plant HiFi and ONT and get the error pasted below. I would greatly appreciate any help figuring out how to move forward.  Thanks!

MBG Branch master commit f9303c51cdbaed401d199d18290638c4b37f61c5 2023-01-17 13:53:23 +0200
Parameters: k=1001,w=100,a=1,u=2,t=4,r=15000,R=4000,hpcvariantcov=25,errormasking=collapse-msat,endkmers=no,blunt=no,keepgaps=no,guesswork=yes,copycountfilter=no,onlylocal=no,cache=no
Collecting hpc variant k-mers
Reading sequences from ../hifi-corrected.fasta.gz
513709214 total selected k-mers in reads
137912719 distinct selected k-mers in reads
Reading sequences from ../hifi-corrected.fasta.gz
Collecting selected k-mers
Reading sequences from ../hifi-corrected.fasta.gz
513709214 total selected k-mers in reads
137914062 distinct selected k-mers in reads
Unitigifying
Filtering by unitig coverage
4684564 distinct selected k-mers in unitigs after filtering
Getting read paths
Reading sequences from ../hifi-corrected.fasta.gz
Resolving unitigs
1086386 unitigs before resolving
estimated average coverage 8.72569
6354302 raw read paths
6394203 raw read paths
2694860 read paths
removed 26387 tips
removed 54 crosslinks
removed 4045 nodes and 1 edges
try resolve k=1001unresolvable even length exact palindrome frozen, id: 492957
unresolvable even length exact palindrome frozen, id: 725696
unresolvable even length exact palindrome frozen, id: 118815
, replaced 28232 nodes with 109561 nodes, unitigified 182177 nodes to 67178 nodes
removed 4201 nodes and 161 edges
MBG: src/UnitigResolver.cpp:954: void addPathButFirstMaybeTrim(ResolvableUnitigGraph&, std::vector<PathGroup>&, PathGroup&&): Assertion `newPath.path.size() > 0' failed.
./buildGraph.sh: line 41: 58078 Aborted                 /public/groups/meyerlab/software/MBG/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --hpc-variant-onecopy-coverage 25 --do-unsafe-guesswork-resolutions --out ../1-buildGraph/hifi-resolved.gfa

**Comment by maickrau** [comment]
This should be fixed in b706a44, could you try with that and then close if it works

**Comment by maickrau** [comment]
Could you please share `hifi-corrected.fasta.gz`?

**Comment by slmcevoy** [comment]
I have temporarily made the file available here: http://public.gi.ucsc.edu/~sumcevoy/
Thanks for looking into it!

**Comment by slmcevoy** [comment]
Hi Mikko,  Were you able to access the file ok?  I would like to remove it from that location if so.

**Comment by maickrau** [comment]
Yes, I was able to download them and you can remove them.

**Comment by maickrau** [comment]
This should now work with commit [1611e9f](https://github.com/maickrau/MBG/commit/1611e9fdd28b89036e77d735915d3ec3ca63282e)

**Comment by slmcevoy** [comment]
It successfully ran without any issues.  Thanks so much for the fix!
