### ISSUE TITLE
Assertion error in running MBG

### ISSUE THREAD

**Issue by wzboy1984** [maickrau/MBG#21]
Dear author,

I encountered an assertion error in running MBG. The error message is as follows:
......
try resolve k=14999, replaced 0 nodes with 0 nodes
102149 unitigs after resolving
Building unitig sequences
Reading sequences from ass1/hifi-corrected.fasta.gz
MBG: src/ConsensusMaker.cpp:240: std::pair<std::vector<CompressedSequence>, StringIndex> ConsensusMaker::getSequences(): Assertion `maxCount > 0' failed.

My command line is:
MBG -i ass1/hifi-corrected.fasta.gz -t 16 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ass1/5.mbg/paths.gaf --hpc-variant-onecopy-coverage 20 --do-unsafe-guesswork-resolutions --out ass1/5.mbg/hifi-resolved.gfa

What should I do to avoid this error?

Best wishes,

**Comment by maickrau** [comment]
This is a bug in MBG. Could you upload `hifi-corrected.fasta.gz`?

**Comment by wzboy1984** [comment]
I've uploaded the file:
https://www.udrop.com/87Jc/hifi-corrected.fasta.gz

**Comment by maickrau** [comment]
I couldn't reproduce the bug with the latest commit. Could you please check which version of MBG you are using, and try with the latest commit in master branch?
