### ISSUE TITLE
loadReadsAsHashesMultithread assertion failed

### ISSUE THREAD

**Issue by grinning-bat** [maickrau/MBG#28]
Hi!
I'm running MBG as a part of verkko, but seems that the error is on the MBG side:

<pre>
MBG Branch master commit c26721b2de0b6f3785deb8922a0e14cab04c2291 2024-02-17 14:57:10 +0200
Parameters: k=1001,w=100,a=1,u=2,t=10,r=15000,R=4000,hpcvariantcov=25,errormasking=collapse-msat,endkmers=no,blunt=no,keepgaps=no,guesswork=yes,copycountfilter=no,onlylocal=no,filterwithinunitig=yes,cleaning=yes,cache=no
Collecting hpc variant k-mers
Reading sequences from ../hifi-corrected.fasta.gz
MBG: src/MBG.cpp:61: MBG::loadReadsAsHashesMultithread(HashList&, size_t, const ReadpartIterator&, size_t, std::ostream&)::<lambda(const MBG::ReadInfo&, const MBG::SequenceCharType&, const MBG::SequenceLengthType&, const std::string&, const std::vector<long unsigned int>&, const std::vector<__int128 unsigned>&)>:
 Assertion `last.first == std::numeric_limits<size_t>::max() || pos - lastMinimizerPosition <= kmerSize' failed.
./buildGraph.sh: line 41: 163898 Aborted                 (core dumped) [redacted]/verkko/env/lib/verkko/bin/MBG $iopt -t 10 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.ga
f --hpc-variant-onecopy-coverage 25 --do-unsafe-guesswork-resolutions --out ../1-buildGraph/hifi-resolved.gfa
</pre>

Say if you need "hifi-corrected.fasta.gz", I can upload, but it's  ~9G. Also, can not get core dump, running on HPC cluster with restricted rights unfortunately.

**Comment by maickrau** [comment]
Hi, yes please upload hifi-corrected.fasta.gz

**Comment by grinning-bat** [comment]
Uploaded MBG-28-hifi-corrected.fasta.tgz to ftp.cbcb.umd.edu/incoming/sergek (Hope it's the right place)
md5: e20c61abbc00421c04ee7717d3e855e7

**Comment by maickrau** [comment]
This seems to be caused by one read having the sequence atatgacatgtc repeating for a very long stretch, which due to a strange combination of microsatellite compression and syncmer selection is palindromic over several kb. You can sidestep this bug for now by switching k from 1001 to 1003 with the verkko parameter `--base-k 1003`.

**Comment by grinning-bat** [comment]
Seems to be solved, thanks!
Now it crashes with another error (as two other assemblies do).
