### ISSUE TITLE
Q: runtime behavior with many cores

### ISSUE THREAD

**Issue by ptrebert** [maickrau/MBG#8]
Hi Mikko,

I am in the process of debugging either a software or a hardware problem, and the burden of proof is with me. Can you please comment on the following:

When MBG v1.0.8 is started with many threads (72; `--resolve-maxk` 15001, i.e. it is a "standard" HiFi run), it starts running using all of them, but at some point, it drops to a single thread. Is that expected? When I check the log file, it is at the stage where the following type of progress messages shows up:

```
try resolve k=687, replaced 0 nodes with 0 nodes
try resolve k=741, replaced 0 nodes with 0 nodes
try resolve k=774, replaced 2065 nodes with 8239 nodes, unitigified 14794 nodes to 4886 nodes
removed 4 tips
try resolve k=501, replaced 0 nodes with 0 nodes
try resolve k=517, replaced 0 nodes with 0 nodes
try resolve k=522, replaced 0 nodes with 0 nodes
try resolve k=544, replaced 0 nodes with 0 nodes
try resolve k=610, replaced 0 nodes with 0 nodes
try resolve k=649, replaced 0 nodes with 0 nodes
try resolve k=663, replaced 0 nodes with 0 nodes
try resolve k=668, replaced 0 nodes with 0 nodes
try resolve k=682, replaced 0 nodes with 0 nodes
try resolve k=775, replaced 2029 nodes with 8115 nodes, unitigified 14664 nodes to 4761 nodes
try resolve k=501, replaced 0 nodes with 0 nodes
try resolve k=502, replaced 0 nodes with 0 nodes
try resolve k=504, replaced 0 nodes with 0 nodes
try resolve k=512, replaced 0 nodes with 0 nodes
try resolve k=517, replaced 0 nodes with 0 nodes
try resolve k=522, replaced 0 nodes with 0 nodes
try resolve k=526, replaced 0 nodes with 0 nodes
try resolve k=533, replaced 0 nodes with 0 nodes
try resolve k=539, replaced 0 nodes with 0 nodes
try resolve k=541, replaced 0 nodes with 0 nodes
try resolve k=542, replaced 0 nodes with 0 nodes
[...]
```
The above entries are already from lines 4000+ of the log, so MBG has been doing this for a while.

Thanks!
+Peter

**Comment by maickrau** [comment]
Yes, this is expected. The multiplex DBG algorithm is single threaded. Starting with a higher k will make it faster because usually the smallest k values are much slower to resolve than larger.

**Comment by ptrebert** [comment]
Thanks for clarifying
